# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 10 * * *'
  push:
    branches:
      - main

permissions:
  contents: write
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 8.0.212
      uses: actions/setup-java@v2
      with:
        java-version: 8.0.212
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
    - name: Commit files
      env:
         GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
         GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
         MY_GIT_TOKEN: ${{ secrets.MY_GIT_TOKEN }}
      run: |
         git config --global user.name $GIT_USERNAME
         git config --global user.email $GIT_EMAIL
         git pull
         if ! git diff --quiet --exit-code; then
           git add -f README.md
           git add -f bing-wallpaper.md
           git add -f picture/*
           git add -f docs/*
           git commit -m "update readme.md"
           git push
         fi
